version: "3"

services:
  web1:
    image: nginx:alpine
    ports:
      - 9090:80
    volumes:
      - ./server-1/www:/srv/www
      - ./server-1/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - www
  phpfpm1:
    image: php:fpm-alpine
    volumes:
      - ./server-1/www:/srv/www
    networks:
      - www
  web2:
    image: nginx:alpine
    ports:
      - 9091:80
    volumes:
      - ./server-2/www:/srv/www
      - ./server-2/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - www
  phpfpm2:
    image: php:fpm-alpine
    volumes:
      - ./server-2/www:/srv/www
    networks:
      - www
networks:
  www:
